// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package xenos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileServiceClient interface {
	// Get the Minecraft UUID for a specific, case-insensitive username.
	GetUuid(ctx context.Context, in *UuidRequest, opts ...grpc.CallOption) (*UuidResponse, error)
	// Get the Minecraft UUIDs for specific, case-insensitive usernames.
	GetUuids(ctx context.Context, in *UuidsRequest, opts ...grpc.CallOption) (*UuidsResponse, error)
	// Get the Minecraft profile for a specific UUID.
	GetProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) GetUuid(ctx context.Context, in *UuidRequest, opts ...grpc.CallOption) (*UuidResponse, error) {
	out := new(UuidResponse)
	err := c.cc.Invoke(ctx, "/scrayosnet.xenos.ProfileService/GetUuid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetUuids(ctx context.Context, in *UuidsRequest, opts ...grpc.CallOption) (*UuidsResponse, error) {
	out := new(UuidsResponse)
	err := c.cc.Invoke(ctx, "/scrayosnet.xenos.ProfileService/GetUuids", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/scrayosnet.xenos.ProfileService/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
// All implementations must embed UnimplementedProfileServiceServer
// for forward compatibility
type ProfileServiceServer interface {
	// Get the Minecraft UUID for a specific, case-insensitive username.
	GetUuid(context.Context, *UuidRequest) (*UuidResponse, error)
	// Get the Minecraft UUIDs for specific, case-insensitive usernames.
	GetUuids(context.Context, *UuidsRequest) (*UuidsResponse, error)
	// Get the Minecraft profile for a specific UUID.
	GetProfile(context.Context, *ProfileRequest) (*ProfileResponse, error)
	mustEmbedUnimplementedProfileServiceServer()
}

// UnimplementedProfileServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (UnimplementedProfileServiceServer) GetUuid(context.Context, *UuidRequest) (*UuidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUuid not implemented")
}
func (UnimplementedProfileServiceServer) GetUuids(context.Context, *UuidsRequest) (*UuidsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUuids not implemented")
}
func (UnimplementedProfileServiceServer) GetProfile(context.Context, *ProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedProfileServiceServer) mustEmbedUnimplementedProfileServiceServer() {}

// UnsafeProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileServiceServer will
// result in compilation errors.
type UnsafeProfileServiceServer interface {
	mustEmbedUnimplementedProfileServiceServer()
}

func RegisterProfileServiceServer(s grpc.ServiceRegistrar, srv ProfileServiceServer) {
	s.RegisterService(&ProfileService_ServiceDesc, srv)
}

func _ProfileService_GetUuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UuidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetUuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scrayosnet.xenos.ProfileService/GetUuid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetUuid(ctx, req.(*UuidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetUuids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UuidsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetUuids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scrayosnet.xenos.ProfileService/GetUuids",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetUuids(ctx, req.(*UuidsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scrayosnet.xenos.ProfileService/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetProfile(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileService_ServiceDesc is the grpc.ServiceDesc for ProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scrayosnet.xenos.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUuid",
			Handler:    _ProfileService_GetUuid_Handler,
		},
		{
			MethodName: "GetUuids",
			Handler:    _ProfileService_GetUuids_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _ProfileService_GetProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scrayosnet/xenos/profile.proto",
}
