name: Docker

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        platform:
        - name: 'minimal'
          tag: 'minimal'
          description: 'Minimal Production Image (without external cache)'
          feature: 'default'
        - name: 'testing'
          tag: 'testing'
          description: 'Static Integration Test Image'
          feature: 'static-testing'
        - name: 'redis'
          tag: 'redis'
          description: 'Production Image (with redis cache)'
          feature: 'redis'
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write
      id-token: write
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login into GitHub Container Registry
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=tag
        flavor: |
          latest=false
          suffix=-${{ matrix.variant.tag }}
        labels: |
          org.opencontainers.image.title=xenos (${{ matrix.variant.name }})
          org.opencontainers.image.description=${{ matrix.variant.description }}
          org.opencontainers.image.vendor=Scrayos UG (haftungsbeschränkt)
          org.opencontainers.image.authors=Joshua Dean Küpper <admin@joshua-kuepper.de>, Paul Wagner <github@paulwagner.dev>
          org.opencontainers.image.url=https://github.com/scrayosnet/xenos
          org.opencontainers.image.documentation=https://github.com/scrayosnet/xenos
          org.opencontainers.image.source=https://github.com/scrayosnet/xenos
          org.opencontainers.image.licenses=MIT

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
        context: .
        build-args: |
          "FEATURES=${{ matrix.variant.feature }}"
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        annotations: ${{ steps.meta.outputs.annotations }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: false
        sbom: false
