name: Build and Release Binaries

on:
  release:
    types:
    - published

jobs:
  build:
    strategy:
      matrix:
        include:
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
        - target: x86_64-apple-darwin
          os: macos-latest
        - target: x86_64-pc-windows-msvc
          os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Apply caching
      uses: swatinem/rust-cache@v2

    - name: Install protoc
      uses: arduino/setup-protoc@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Upload binary
      uses: taiki-e/upload-rust-binary-action@v1
      with:
        bin: mcexport
        target: ${{ matrix.target }}
        tar: unix
        zip: windows
        token: ${{ secrets.GITHUB_TOKEN }}
