on: [push]

jobs:
  deploy:
    name: Deploy to Cloudflare Workers with Wrangler
    uses: cloudflare/wrangler-action@v3
    with:
      apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
